//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agendamento.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL
    {
        public int ID_EMAIL { get; set; }
        public string TIPO_EMAIL { get; set; }
        public int AGENDA_ID_AGENDA { get; set; }
        public string EMAIL1 { get; set; }
    
        public virtual AGENDA AGENDA { get; set; }
    }
}
